### ISSUE TITLE
OXS下执行命令保报错

### ISSUE THREAD

**Issue by xiezefan** [leizongmin/programmer-calendar#1]
```
XieZefan-MBP:resources xiezefan$ programmer-calendar
/usr/local/lib/node_modules/programmer-calendar/bin/calendar.js:15
const path = require('path');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

环境：
- node:v0.12.2
- nam:2.12.1

**Comment by xiezefan** [comment]
使用   

```
node --harmony /usr/local/lib/node_modules/programmer-calendar/bin/calendar.js 
```

启动程序可解决问题，不过作者最好还是少用const ：）

**Comment by leizongmin** [comment]
为了推动Node4.x版本的普及，请安装LTS最新版：

``` bash
$ npm install -g n
$ n 4.2.3
```
